
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ta-backend
    ports:
      - "3000:5000"
    volumes:
      - ./Backend:/Backend
    command: python app/main.py

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ta-frontend
    ports:
      - "80:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
    depends_on:
      - backend